apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "base.name" . }}
          image: eurodatacube/lpvis-edc:{{ .Chart.Version }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-{{ include "base.name" . }}
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-{{ include "base.name" . }}
                  key: db_database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-{{ include "base.name" . }}
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-{{ include "base.name" . }}
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-{{ include "base.name" . }}
                  key: db_password
            - name: SH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-{{ include "base.name" . }}
                  key: client_id
            - name: SH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-{{ include "base.name" . }}
                  key: client_secret
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.1"
              memory: "32Mi"
      nodeSelector: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - user
      tolerations: []
