apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # force k8s to restart pod to apply config changes
        # https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        rollme: {{ randAlphaNum 5 | quote }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: {{ include "base.fullname" . }}
      containers:
      - name: byoa-results
        image: 'registry.gitlab.eox.at/esa/dcfs/byoa-results:{{ .Chart.AppVersion }}'
        env:
        - name: SCRATCH_BUCKET_NAME
          value: {{ .Values.scratchBucketName }}
        - name: MARKETPLACE_API_URL
          value: "https://api.hub.eox.at"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 3
        resources:
          limits:
            cpu: 0.1
            memory: 192Mi
          requests:
            cpu: 0.05
            memory: 64Mi
        imagePullPolicy: Always
      - name: watch-result-secrets
        image: 'registry.gitlab.eox.at/esa/dcfs/byoa-results:{{ .Chart.AppVersion }}'
        command: ["tini", "--", "python3", "watch_result_secrets.py"]
        env:
        - name: SCRATCH_BUCKET_NAME
          value: {{ .Values.scratchBucketName }}
        - name: MARKETPLACE_API_URL
          value: "https://api.hub.eox.at"
        resources:
          limits:
            cpu: 0.1
            memory: 192Mi
          requests:
            cpu: 0.05
            memory: 64Mi
        imagePullPolicy: Always
      - name: watch-sync-jobs
        image: 'registry.gitlab.eox.at/esa/dcfs/byoa-results:{{ .Chart.AppVersion }}'
        command: ["tini", "--", "python3", "watch_sync_jobs.py"]
        env:
        - name: SCRATCH_BUCKET_NAME
          value: {{ .Values.scratchBucketName }}
        - name: MARKETPLACE_API_URL
          value: "https://api.hub.eox.at"
        resources:
          limits:
            cpu: 0.1
            memory: 192Mi
          requests:
            cpu: 0.05
            memory: 64Mi
        imagePullPolicy: Always
      imagePullSecrets:
      - name: {{ include "base.fullname" . }}-image-pull
      nodeSelector: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - user
      tolerations: []
