apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "base.fullname" . }}
rules:
  - apiGroups: [""]
    verbs: ["list", "watch", "get", "patch", "create", "delete"]
    resources:
      - secrets

