apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  type: ExternalName
  externalName: ogc-edc-tb16-dapa.hub.eox.at
