{{- $fullName := include "base.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "base.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: http
        path: /
  {{ if ne .Release.Name "byoa-results" }}
  # We generate links to this subdomain, the app must be available here
  - host: byoa-results.{{ .Release.Namespace }}.hub.eox.at
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: http
        path: /
  {{ end }}
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
    secretName: wildcard-tls
  {{ if ne .Release.Name "byoa-results" }}
  - hosts:
    - byoa-results.{{ .Release.Namespace }}.hub.eox.at
    secretName: wildcard-tls
  {{ end }}

