apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "base.fullname" . }}
rules:
  - apiGroups: [""]
    verbs: ["list", "watch", "get", "patch", "create"]
    resources:
      - secrets
  - apiGroups: ["batch"]
    verbs: ["create", "list"]
    resources:
      - jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "base.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "base.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "base.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
