apiVersion: v1
data:
  # NOTE: this secret allows access to the docker images, and since this  file is public, 
  #       this makes the images effectively publicly accessible
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuZW94LmF0Ijp7InVzZXJuYW1lIjoiZmx1eC1ieW9hLXJlc3VsdHMiLCJwYXNzd29yZCI6Ik02WUtxRHhHeFRRY05BWTNkc3JRIiwiZW1haWwiOiJodWJAZW94LmF0IiwiYXV0aCI6IlpteDFlQzFpZVc5aExYSmxjM1ZzZEhNNlRUWlpTM0ZFZUVkNFZGRmpUa0ZaTTJSemNsRT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "base.fullname" . }}-image-pull
type: kubernetes.io/dockerconfigjson
