
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # force k8s to restart pod to apply config changes
        # https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ include "base.name" . }}
          image: eurodatacube/24ba82dc-b1a2-43cb-b98b-b112093a1a26:{{ .Chart.Version }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: SH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-{{ include "base.name" . }}
                  key: client_id
            - name: SH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-{{ include "base.name" . }}
                  key: client_secret
            - name: SH_INSTANCE_ID
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-{{ include "base.name" . }}
                  key: instance_id
            - name: GEODB_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-default
                  key: auth_client_id
            - name: GEODB_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-default
                  key: auth_client_secret
            - name: GEODB_AUTH_AUD
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-default
                  key: auth_aud
            - name: GEODB_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-default
                  key: auth_domain
            - name: GEODB_API_SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-default
                  key: api_server_port
            - name: GEODB_API_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: eurodatacube-geodb-default
                  key: api_server_url
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          resources:
            limits:
              cpu: "200m"
              memory: "800M"
            requests:
              cpu: "100m"
              memory: "400M"
      nodeSelector: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - user
      tolerations: []