{{- $fullName := include "base.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "base.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-vhost: xcube-gen.brockmann-consult.de
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    # this is a reimplementation of the "app-root" annotation, but
    # if done like this, CORS headers are actually sent.
    nginx.ingress.kubernetes.io/configuration-snippet: 'location = "/" { return 302 /viewer/; } '
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 443
            path: /
  tls:
    - hosts:
        - {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
      secretName: {{ $fullName }}-tls
