apiVersion: v1
appVersion: "v1.0"
description: lpvis-edc
name: lpvis-edc
version: 0.2.1
keywords:
  - LPIS
  - Datacube
maintainers:
  - name: Euro Data Cube
    url: www.eurodatacube.com
icon: https://cockpit.hub.eox.at/storage/uploads/2019/09/12/5d7a0b3e162f4EDC_logo_square_blue.png
