apiVersion: v1
appVersion: v1.0
description: SHM Request Timer
icon: https://raw.githubusercontent.com/eurodatacube/charts/master/poll-shm/stopwatch-34108.png?sanitize=true
keywords:
- license:Commercial
- "license_notes:"
- license_price:1
- requirement:eurodatacube
- requirement:eoxhub
- tag:Sentinel Hub
- tag:Mass Processing
maintainers:
- name: 910be60e-784b-44e4-9d4e-06ff086b660f
name: poll-shm
sources:
- StefanBrand/poll-shm
version: 0.1.0
