kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "base.fullname" . }}-config
  labels:
{{ include "base.labels" . | indent 4 }}
data:
  config.yaml: |
    DatasetAttribution:
      - "© by Brockmann Consult GmbH 2023"
      - "© by ESA Data Cube Facility Service (DCFS) project"

    DatasetChunkCacheSize: 500M

    base_dir: s3://xcube-viewer-app/edc/prod ## <- here we would need a place in EDC to store additional material, as e.g. the viewer configuration.

    Viewer:
      Configuration:
        Path: viewer

    DataStores:
      - Identifier: edc
        StoreId: s3
        StoreParams:
          root: xcube-dcfs/edc-xc-viewer-data
          storage_options:
            anon: true
        Datasets:
          - Path: HH_CityCube_RGB.zarr
            Style: default
            # ChunkCacheSize: 1G

      - Identifier: cop
        StoreId: s3
        StoreParams:
          root: xcube-dcfs/edc-xc-viewer-data/cop
          max_depth: 1
          storage_options:
            anon: true
        Datasets:
          - Path: CMEMS_OC_ATL.zarr
            Title: CMEMS OC Atlantic
            Style: default
            TimeSeriesDataset: cmems-oc-atl-time-optimised

          - Identifier: cmems-oc-atl-time-optimised
            Title: CMEMS OC ATL Time Chunked
            Path: CMEMS_OC_ATL-128x219x512.zarr
            Hidden: true

          - Path: CMEMS_OC_BS_4.zarr
            Title: CMEMS OC Black Sea
            Style: default
            TimeSeriesDataset: cmems-oc-bs-time-optimised

          - Identifier: cmems-oc-bs-time-optimised
            Title: CMEMS OC BS Time Chunked
            Path: CMEMS_OC_BS_4-397x133x128.zarr
            Hidden: true

    Styles:
      - Identifier: default
        ColorMappings:
          CHL:
            ColorFile: ../custom_colormaps/chl_DeM2.cpd
          MCI:
            ColorBar: CMRmap
            ValueRange: [0., 0.008]
          B02:
            ColorBar: bone
            ValueRange: [0., 0.25]
          B03:
            ColorBar: bone
            ValueRange: [0., 0.25]
          B04:
            ColorBar: bone
            ValueRange: [0., 0.25]
          B05:
            ColorBar: bone
            ValueRange: [0., 0.25]
          B06:
            ColorBar: bone
            ValueRange: [0., 0.25]
          B08:
            ColorBar: bone
            ValueRange: [0., 0.25]
          rgb:
            Red:
              Variable: B04
              ValueRange: [0., 0.25]
            Green:
              Variable: B03
              ValueRange: [0., 0.25]
            Blue:
              Variable: B02
              ValueRange: [0., 0.25]

      - Identifier: s2
        ColorMappings:
          Chlorophyll:
            ColorBar: plasma
            ValueRange: [0., 40.]
          secci_depth:
            ColorBar: Blues
            ValueRange: [0., 20.]
          Turbidity:
            ColorFile: ../custom_colormaps/Bfg_schweb_50.cpd
          immersed_cyanobacteria:
            ColorBar: Reds
            ValueRange: [0, 1.]
          rgb:
            Red:
              Variable: rtoa_B4
              ValueRange: [0., 0.25]
            Green:
              Variable: rtoa_B3
              ValueRange: [0., 0.25]
            Blue:
              Variable: rtoa_B2
              ValueRange: [0., 0.25]


    ServiceProvider:
      ProviderName: Brockmann Consult GmbH
      ProviderSite: https://www.brockmann-consult.de
      ServiceContact:
        IndividualName: Alicja Balfanz
        ContactInfo:
          Phone:
            Voice: +49 40 696 389 300
            Facsimile: +49 40 696 389 399
          Address:
            DeliveryPoint: Chrysanderstr. 1
            City: Hamburg
            AdministrativeArea: Hamburg
            PostalCode: 21029
            Country: Germany
            ElectronicMailAddress: info@brockmann-consult.de
