
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # force k8s to restart pod to apply config changes
        # https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ include "base.name" . }}
          image: eurodatacube/xcube:{{ .Chart.AppVersion }}
          ports:
            - name: http
              containerPort: 9988
              protocol: TCP
          volumeMounts:
            - name: xcube-config
              mountPath: /config.yaml
              subPath: config.yaml
          command: ["xcube", "--traceback", "--loglevel", "INFO", "-a", "0.0.0.0:9988", "-c", "/config.yaml"]
          resources:
            limits:
              cpu: "200m"
              memory: "800M"
            requests:
              cpu: "100m"
              memory: "400M"
      volumes:
      - name: xcube-config
        configMap:
          name: {{ include "base.fullname" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - user
      tolerations: []
