
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # force k8s to restart pod to apply config changes
        # https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ include "base.name" . }}
          image: eurodatacube/xcube:{{ .Chart.AppVersion }}
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: xcube-viewer-bucket
                key: username
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: xcube-viewer-bucket
                key: password
          ports:
            - name: http
              containerPort: 9988
              protocol: TCP
          volumeMounts:
            - name: bucket-config
              mountPath: /config.yaml
              subPath: config.yaml
            - name: bucket-config
              mountPath: /home/xcube/viewer
              subPath: viewer
          command: ["/opt/conda/bin/xcube", "--traceback", "--loglevel", "INFO", "serve", "-p", "9988", "-c", "/config.yaml"]
          resources:
            limits:
              cpu: "400m"
              memory: "3G"
            requests:
              cpu: "100m"
              memory: "400M"
      initContainers:
      - name: s3-mounter
        image: totycro/s3fs:0.13.0-1.91
        args: ["sh", "-x", "/bucket-copy-script/copy_from_bucket.sh"]
        volumeMounts:
          - name: bucket-config
            mountPath: /bucket-config
          - name: bucket-copy-script
            mountPath: /bucket-copy-script
        env:
        - name: INGRESS_BASE
          value: "https://{{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at"
        - name: S3FS_ARGS
          value: "-oallow_other -oro"
        - name: AWS_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: xcube-viewer-bucket
              key: username
        - name: AWS_S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: xcube-viewer-bucket
              key: password
        - name: AWS_S3_BUCKET
          value: edc-xcube-viewer-demo:/
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.1"
            memory: 128Mi

      volumes:
      - name: xcube-config
        configMap:
          name: {{ include "base.fullname" . }}
      - name: bucket-copy-script
        configMap:
          name: {{ include "base.fullname" . }}-bucket-copy-script
      - name: bucket-config
        emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - user
      tolerations: []
