{{- $fullName := include "base.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "base.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/app-root: /viewer
    # nginx.ingress.kubernetes.io/configuration-snippet" = "if ($request_uri !~* ^/(api|assets)) { rewrite ^/.*$ / break; }
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2  # Here we concatenate the two matched groups

spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              name: http
        path: /api/()(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ $fullName }}
            port:
              name: http
        path: /(viewer)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
    secretName: wildcard-tls
