apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "base.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # force k8s to restart pod to apply config changes
        # https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccountName: {{ include "base.fullname" . }}
      containers:
        - name: {{ include "base.name" . }}
          image: eurodatacube/pygeoapi-eoxhub:{{ .Chart.Version }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /conformance
              port: 80
          readinessProbe:
            httpGet:
              path: /conformance
              port: 80
          resources:
            limits:
              cpu: "200m"
              memory: "800M"
            requests:
              cpu: "100m"
              memory: "400M"
          volumeMounts:
          - name: pygeoapi-config
            mountPath: "/pygeoapi/local.config.yml"
            subPath: local.config.yml
          {{ if .Values.existingNfs.enabled }}
          - name: user-home
            # mount same as actual user pod such that we don't have to translate dirs
            mountPath: /home/jovyan
          {{ end }}
          {{ range $pvcIndex, $extraPvc := .Values.extraPvcs }}
          - name: extra-{{ $pvcIndex }}
            mountPath: {{ $extraPvc.mount_path }}
          {{ end }}
      volumes:
      - name: pygeoapi-config
        configMap:
          name: {{ include "base.fullname" . }}
      {{ if .Values.existingNfs.enabled }}
      - name: user-home
        persistentVolumeClaim:
          claimName: user
      {{ end }}
      {{ range $pvcIndex, $extraPvc := .Values.extraPvcs }}
      - name: extra-{{ $pvcIndex }}
        persistentVolumeClaim:
          claimName: {{ $extraPvc.claim_name }}
      {{ end }}
      nodeSelector: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - user
      tolerations: []
