{{- $fullName := include "base.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "base.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
  - host: {{ include "base.ingressUrl" . }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: http
        path: /
  tls:
  - hosts:
    - {{ include "base.ingressUrl" . }}
    secretName: wildcard-tls
