{{- $fullName := include "base.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "base.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-vhost: snow-app-gte2s.hub.eox.at
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: 443
            path: /
  tls:
    - hosts:
        - {{ .Release.Name }}.{{ .Release.Namespace }}.hub.eox.at
      secretName: wildcard-tls
