{{ if .Values.enableEoxhubGatewayService }}
# EOXHub gateway is looking for a service named `pygeoapi`
# for service autodetection, so provide an extra service
# here.
# We don't autodetect the default service because
# that would enable it everywhere automatically.
apiVersion: v1
kind: Service
metadata:
  name: pygeoapi
  labels:
{{ include "base.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "base.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
