existingNfs:
  enabled: true
  nfsServer: "fs-67cadc3e.efs.eu-central-1.amazonaws.com"
  nfsShare: "edc-jupyter-user-pvc-3157bd51-f57d-11e9-adac-062139e27092"


extraPvcs: []
  #- claim_name: ama-jupyter-eox
  #  mount_path: /home/jovyan/eox


defaultImage: "eurodatacube/jupyter-user:0.22.1"
imagePullSecret: ""

s3:
  enabled: false
  bucketName: ""
  secretName: "s3-bucket"

jupyterBaseUrl: "https://edc-jupyter.hub.eox.at"

outputDirectory: "/home/jovyan/job-output"
